# Generated by Django 5.2.6 on 2025-09-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='card',
            name='set_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
