# Generated by Django 5.2.6 on 2025-09-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_card_number_card_price_card_set_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('double rare', 'Double Rare'), ('ace spec rare', 'Ace Spec Rare'), ('illustration rare', 'Illustration Rare'), ('ultra rare', 'Ultra Rare'), ('special illustration rare', 'Special Illustration Rare'), ('hyper rare', 'Hyper Rare'), ('shiny rare', 'Shiny Rare'), ('shiny ultra rare', 'Shiny Ultra Rare'), ('black star promo', 'Black Star Promo')], default='common', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='set_name',
            field=models.CharField(max_length=100),
        ),
    ]
