# Generated by Django 5.2.6 on 2025-09-26 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_card_rarity_alter_card_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='grading',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='gradingCompany',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(help_text='Format: X/Y, e.g., 171/86', max_length=10, validators=[django.core.validators.RegexValidator(message='Number must be in format X/Y (e.g., 171/86)', regex='^\\d+/\\d+$')]),
        ),
        migrations.AlterField(
            model_name='card',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('double rare', 'Double Rare'), ('ace spec rare', 'Ace Spec Rare'), ('illustration rare', 'Illustration Rare'), ('ultra rare', 'Ultra Rare'), ('special illustration rare', 'Special Illustration Rare'), ('hyper rare', 'Hyper Rare'), ('shiny rare', 'Shiny Rare'), ('shiny ultra rare', 'Shiny Ultra Rare'), ('black star promo', 'Black Star Promo'), ('black white rare', 'Black White Rare')], default='common', max_length=50),
        ),
    ]
